#!/usr/bin/env bash
# Test double for sudo: consumes the password line (-S), ignores -p/-u, runs the command as the caller.
IFS= read -r _password
while [[ $# -gt 0 ]]; do
    case "$1" in
        -S|-n) shift ;;
        -p|-u) shift 2 ;;
        --) shift; break ;;
        *) break ;;
    esac
done
exec "$@"
